# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2.1

# Personal info
name: Ruslan
title: Software Developer
email: rus@0x2.dev
website: www.0x2.dev

# Dark Mode (true/false/never)
darkmode: never

# Social links
# twitter_username: facespics
github_username: roosslan
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
linkedin_username: ruslan
xing_username: ruslan
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0009-0009-1412-6089

# Additional icon links
additional_links:
- title: 0x.be
  icon: fas fa-globe
  url: https://www.0x.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.png
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Ruslan and I'm a software developer. As well as programming I also have experience making software and Windows apps. I have worked at a number of companies gaining teamwork.

  I am most skilled in: <mark>OOP</mark> and <mark>C++</mark>

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: winralter
        link: www.0x2.dev
        # link_text: Project Website
        additional_links:
          - title:  sproogen/modern-resume-theme
            icon: fab fa-github
            url: github.com/roosslan/winralter
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          This is one of the apps I've created.
        description: | # this will include new lines to allow paragraphs
          I started this project as a way if learning <mark>React</mark> and it has since grown into a fully fledged app. I have learned many skills through this and been I'm very proud of having this in my portfolio. If you don't have a project as awesome as this I would advise you make one.

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Freelance
        link: boringcompany.com
        # link_text: boringcompany.com
        sub_title: C++ developer
        caption: Oct 2022 - Present
        quote: >
          Solving 21st century problems by coding
        description: | # this will include new lines to allow paragraphs
            git, Unit Tests, Eclipse, Jira.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: KAI University
        caption: 2006 - 2011
        sub_title: BSc Computer Science
        quote: >
          Established in 1932, Aviation University is the oldest higher education institution, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in the world.
        description: | # this will include new lines to allow paragraphs
          During my time at KNITU I learnt most of my key skills that have I have taken through my career such as teamwork and working to tight deadlines. I thouroughly enjoyed my time as university and learnt a lot about a healthy work life balance.

          I spent a lot of my free time as a committee member of the *KAI Mountaineering Club* taking on roles such as *Trip Secretary* and *Vice-President*.

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in networks and software engineering some of my other interests and hobbies are:
      - Chess
      - Swimming
      - Soldering
      - Sci-fi Books

      Some image  
      ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
